# Generated by Django 4.1.4 on 2023-01-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=64)),
                ("comision", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Entregable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=256)),
                ("fecha_entrega", models.DateTimeField()),
                ("esta_aprobado", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Estudiantes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=256)),
                ("apellido", models.CharField(max_length=256)),
                ("dni", models.CharField(max_length=32)),
                ("email", models.EmailField(max_length=254)),
                ("fecha_nacimiento", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=256)),
                ("apellido", models.CharField(max_length=256)),
                ("dni", models.CharField(max_length=32)),
                ("email", models.EmailField(max_length=254)),
                ("fecha_nacimiento", models.DateField()),
                ("profesion", models.CharField(max_length=128)),
                ("bio", models.TextField()),
            ],
        ),
    ]
