# Generated by Django 4.1.4 on 2023-01-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudiantes", "0003_instituto_alter_estudiante_fecha_nacimiento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="fecha_inicio",
            field=models.DateField(null=True),
        ),
    ]
