# Generated by Django 4.1.4 on 2023-01-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudiantes", "0004_curso_fecha_inicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="descripcion",
            field=models.TextField(null=True),
        ),
    ]
